import { AccountSettings, Account, AccountRole } from "./auth";
export type From = "in" | "out";

export interface Message {
	id: number;
	from: From;
	text: string;
}

const MOCK_PASSWORD = "mock-hash";
const MOCK_CREATED_AT = Date.now();

const defaultSettings = (): AccountSettings => ({
	emailNotificationsEnabled: true,
	pushNotificationsEnabled: false,
	requestAlerts: false,
	digestWeekday: "Friday",
	digestTime: "08:00",
	digestEnabled: false,
	availability: true,
	resourceRemindersEnabled: false,
	mapAlertsEnabled: false,
	smsUrgentAlertsEnabled: false,
});

export const students: Account[] = [
	{
		id: 1,
		email: "avery.kim@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Avery Kim",
			firstName: "Avery",
			lastName: "Kim",
			grade: "8",
			bio: "I enjoy robotics, science fairs, and exploring how machines work. Excited to join STEM Club!",
			interests: ["robotics", "science fairs", "engineering"],
		},
		settings: defaultSettings(),
		wentThroughOnboarding: true,
	},
	{
		id: 2,
		email: "marcus.tran@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Marcus Tran",
			firstName: "Marcus",
			lastName: "Tran",
			grade: "7",
			bio: "I love playing soccer, coding small games, and building things with my friends.",
			interests: ["soccer", "coding", "making"],
		},
		settings: defaultSettings(),
	},
	{
		id: 3,
		email: "sophie.li@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Sophie Li",
			firstName: "Sophie",
			lastName: "Li",
			grade: "6",
			bio: "I'm new to coding but love drawing, baking, and solving puzzles. Excited to make new friends!",
			interests: ["drawing", "baking", "puzzles"],
		},
		settings: defaultSettings(),
	},
	{
		id: 4,
		email: "noah.garcia@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Noah Garcia",
			firstName: "Noah",
			lastName: "Garcia",
			grade: "8",
			bio: "I'm part of band and enjoy practicing guitar, helping with stage crew, and trying out 3D printing.",
			interests: ["band", "guitar", "stage crew", "3D printing"],
		},
		settings: defaultSettings(),
	},
	{
		id: 5,
		email: "mia.patel@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Mia Patel",
			firstName: "Mia",
			lastName: "Patel",
			grade: "7",
			bio: "I love art and design, journaling, and volunteering for school events.",
			interests: ["art", "design", "journaling", "volunteering"],
		},
		settings: defaultSettings(),
	},
	{
		id: 6,
		email: "ethan.reyes@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Ethan Reyes",
			firstName: "Ethan",
			lastName: "Reyes",
			grade: "8",
			bio: "I enjoy math challenges, robotics, and helping my classmates learn coding basics.",
			interests: ["math", "robotics", "tutoring"],
		},
		settings: defaultSettings(),
	},
	{
		id: 7,
		email: "zara.thompson@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Zara Thompson",
			firstName: "Zara",
			lastName: "Thompson",
			grade: "6",
			bio: "I'm into digital art, reading fantasy novels, and learning photography.",
			interests: ["digital art", "fantasy", "photography"],
		},
		settings: defaultSettings(),
	},
	{
		id: 8,
		email: "leo.chen@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Leo Chen",
			firstName: "Leo",
			lastName: "Chen",
			grade: "7",
			bio: "I'm into robotics, coding challenges, and building model rockets with my friends.",
			interests: ["robotics", "coding challenges", "model rockets"],
		},
		settings: defaultSettings(),
	},
	{
		id: 9,
		email: "aria.johnson@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Aria Johnson",
			firstName: "Aria",
			lastName: "Johnson",
			grade: "8",
			bio: "I love creative writing, theater, and leading small group projects at school.",
			interests: ["creative writing", "theater", "leadership"],
		},
		settings: defaultSettings(),
	},
	{
		id: 10,
		email: "caleb.nguyen@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Caleb Nguyen",
			firstName: "Caleb",
			lastName: "Nguyen",
			grade: "6",
			bio: "I enjoy soccer, experimenting with Arduino kits, and building fun contraptions at home.",
			interests: ["soccer", "arduino", "maker"],
		},
		settings: defaultSettings(),
	},
	{
		id: 11,
		email: "isabella.rivera@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Isabella Rivera",
			firstName: "Isabella",
			lastName: "Rivera",
			grade: "7",
			bio: "I'm interested in journalism, photography, and storytelling through visuals.",
			interests: ["journalism", "photography", "storytelling"],
		},
		settings: defaultSettings(),
	},
	{
		id: 12,
		email: "liam.morales@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Liam Morales",
			firstName: "Liam",
			lastName: "Morales",
			grade: "8",
			bio: "I'm passionate about environmental science, student leadership, and recycling projects.",
			interests: ["environment", "leadership", "recycling"],
		},
		settings: defaultSettings(),
	},
	{
		id: 13,
		email: "chloe.park@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Chloe Park",
			firstName: "Chloe",
			lastName: "Park",
			grade: "6",
			bio: "I love animals, art club, and learning to code small games in Scratch.",
			interests: ["animals", "art club", "Scratch"],
		},
		settings: defaultSettings(),
	},
	{
		id: 14,
		email: "owen.flores@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Owen Flores",
			firstName: "Owen",
			lastName: "Flores",
			grade: "7",
			bio: "I'm into robotics, gaming, and learning about how computers actually work.",
			interests: ["robotics", "gaming", "computer science"],
		},
		settings: defaultSettings(),
	},
	{
		id: 15,
		email: "luna.delgado@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Luna Delgado",
			firstName: "Luna",
			lastName: "Delgado",
			grade: "8",
			bio: "I enjoy theater, dance, and creative storytelling. Excited to meet new people this year!",
			interests: ["theater", "dance", "storytelling"],
		},
		settings: defaultSettings(),
	},
	{
		id: 16,
		email: "eli.ross@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Eli Ross",
			firstName: "Eli",
			lastName: "Ross",
			grade: "7",
			bio: "I'm into robotics, hiking, and exploring how technology can solve real problems.",
			interests: ["robotics", "hiking", "technology"],
		},
		settings: defaultSettings(),
	},
	{
		id: 17,
		email: "naomi.wu@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Naomi Wu",
			firstName: "Naomi",
			lastName: "Wu",
			grade: "6",
			bio: "I love drawing, piano, and exploring fun science experiments at home.",
			interests: ["drawing", "piano", "science experiments"],
		},
		settings: defaultSettings(),
	},
	{
		id: 18,
		email: "jackson.lee@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Jackson Lee",
			firstName: "Jackson",
			lastName: "Lee",
			grade: "8",
			bio: "I'm a member of chess club, coding club, and I like building mechanical projects with my dad.",
			interests: ["chess", "coding", "mechanical projects"],
		},
		settings: defaultSettings(),
	},
	{
		id: 19,
		email: "sophia.martinez@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Sophia Martinez",
			firstName: "Sophia",
			lastName: "Martinez",
			grade: "7",
			bio: "I love graphic design, yearbook club, and collaborating on group art projects.",
			interests: ["graphic design", "yearbook", "art"],
		},
		settings: defaultSettings(),
	},
	{
		id: 20,
		email: "gabriel.torres@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Gabriel Torres",
			firstName: "Gabriel",
			lastName: "Torres",
			grade: "8",
			bio: "I'm interested in engineering, video editing, and helping out in tech crew events.",
			interests: ["engineering", "video editing", "tech crew"],
		},
		settings: defaultSettings(),
	},
];

export const mentors: Account[] = [
	{
		id: 101,
		email: "mbarrios@wcusd.org",
		password: MOCK_PASSWORD,
		role: "teacher" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Mr. Miguel Barrios",
			firstName: "Miguel",
			lastName: "Barrios",
			mentorType: "teacher",
			mentorBio:
				"I'm passionate about STEM outreach, love a good poker night, and spend weekends hiking. Excited to help students discover hands-on robotics.",
			teacherTitle: "Mr.",
			teacherRoom: "6",
			teacherAvailabilityNotes: "Science — Robotics mentor; office hours Tue/Thu lunch",
		},
		settings: defaultSettings(),
	},
	{
		id: 102,
		email: "jchoi@wcusd.org",
		password: MOCK_PASSWORD,
		role: "teacher" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Ms. June Choi",
			firstName: "June",
			lastName: "Choi",
			mentorType: "teacher",
			mentorBio:
				"I teach history and love exploring art, solving puzzles, and talking about the past in fun ways.",
			teacherTitle: "Ms.",
			teacherRoom: "12",
			teacherAvailabilityNotes: "History — lunch M/W",
		},
		settings: defaultSettings(),
	},
	{
		id: 103,
		email: "pchiang@wcusd.org",
		password: MOCK_PASSWORD,
		role: "teacher" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Ms. Prisha Chiang",
			firstName: "Prisha",
			lastName: "Chiang",
			mentorType: "teacher",
			mentorBio:
				"I'm all about bringing art into the classroom. I help with yearbook and love working on community murals.",
			teacherTitle: "Ms.",
			teacherRoom: "4B",
			teacherAvailabilityNotes: "Visual Arts — after school Tue",
		},
		settings: defaultSettings(),
	},
	{
		id: 104,
		email: "mcisneros@wcusd.org",
		password: MOCK_PASSWORD,
		role: "teacher" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Ms. Marina Cisneros",
			firstName: "Marina",
			lastName: "Cisneros",
			mentorType: "teacher",
			mentorBio:
				"I'm passionate about creative writing, student journalism, and fostering a love of reading.",
			teacherTitle: "Ms.",
			teacherRoom: "17",
			teacherAvailabilityNotes: "ELA — Thu after school",
		},
		settings: defaultSettings(),
	},
	{
		id: 105,
		email: "deich@wcusd.org",
		password: MOCK_PASSWORD,
		role: "teacher" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Mr. Daniel Eich",
			firstName: "Daniel",
			lastName: "Eich",
			mentorType: "teacher",
			mentorBio:
				"I love mentoring students for science fairs, gardening on campus, and showcasing robotics projects.",
			teacherTitle: "Mr.",
			teacherRoom: "18",
			teacherAvailabilityNotes: "Science — Mon/Wed after school",
		},
		settings: defaultSettings(),
	},
	{
		id: 106,
		email: "pfischer@wcusd.org",
		password: MOCK_PASSWORD,
		role: "teacher" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Mr. Paul Fischer",
			firstName: "Paul",
			lastName: "Fischer",
			mentorType: "teacher",
			mentorBio:
				"History bowl coach and avid hiker who loves visiting museums with students.",
			teacherTitle: "Mr.",
			teacherRoom: "13",
			teacherAvailabilityNotes: "Social Studies — Tue lunch",
		},
		settings: defaultSettings(),
	},
	{
		id: 107,
		email: "kgarcia@wcusd.org",
		password: MOCK_PASSWORD,
		role: "teacher" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Ms. Kat Garcia",
			firstName: "Kat",
			lastName: "Garcia",
			mentorType: "teacher",
			mentorBio:
				"I work in counseling and love mindfulness, student leadership, and helping students find their path.",
			teacherTitle: "Ms.",
			teacherRoom: "Counseling",
			teacherAvailabilityNotes: "Counseling & Student Support — daily office hours",
		},
		settings: defaultSettings(),
	},
	{
		id: 108,
		email: "isalazar@wcusd.org",
		password: MOCK_PASSWORD,
		role: "teacher" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Ms. Isa Salazar",
			firstName: "Isa",
			lastName: "Salazar",
			mentorType: "teacher",
			mentorBio:
				"STEM educator who loves science labs, introducing students to coding, and going on hikes.",
			teacherTitle: "Ms.",
			teacherRoom: "10",
			teacherAvailabilityNotes: "STEM — Wed after school",
		},
		settings: defaultSettings(),
	},
	{
		id: 109,
		email: "gvela@wcusd.org",
		password: MOCK_PASSWORD,
		role: "teacher" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Mr. Gabe Vela",
			firstName: "Gabe",
			lastName: "Vela",
			mentorType: "teacher",
			mentorBio:
				"I mentor robotics teams, work with younger students, and spend weekends playing soccer.",
			teacherTitle: "Mr.",
			teacherRoom: "15",
			teacherAvailabilityNotes: "Engineering & Technology — Tue/Thu lunch",
		},
		settings: defaultSettings(),
	},
	{
		id: 110,
		email: "svilla@wcusd.org",
		password: MOCK_PASSWORD,
		role: "teacher" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Mr. Shawn Villa",
			firstName: "Shawn",
			lastName: "Villa",
			mentorType: "teacher",
			mentorBio: "I run the tech help desk and love esports and photography.",
			teacherTitle: "Mr.",
			teacherRoom: "32",
			teacherAvailabilityNotes: "Information Technology — Fri lunch",
		},
		settings: defaultSettings(),
	},
	{
		id: 111,
		email: "mchen@wcusd.org",
		password: MOCK_PASSWORD,
		role: "teacher" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Ms. Chen",
			firstName: "M.",
			lastName: "Chen",
			mentorType: "teacher",
			mentorBio:
				"I guide our robotics teams, love tinkering with microcontrollers, and host weekly build nights in the tech lab.",
			teacherTitle: "Ms.",
			teacherRoom: "32",
			teacherAvailabilityNotes: "Engineering & Robotics — Wed build nights",
		},
		settings: defaultSettings(),
	},
	{
		id: 112,
		email: "vpatel@wcusd.org",
		password: MOCK_PASSWORD,
		role: "teacher" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Mr. Patel",
			firstName: "V.",
			lastName: "Patel",
			mentorType: "teacher",
			mentorBio:
				"Student leadership advisor focused on empowering voices, planning community events, and growing confident change-makers.",
			teacherTitle: "Mr.",
			teacherRoom: "Counseling",
			teacherAvailabilityNotes: "Student Leadership — daily office hours",
		},
		settings: defaultSettings(),
	},
	{
		id: 113,
		email: "arivera@wcusd.org",
		password: MOCK_PASSWORD,
		role: "teacher" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Ms. Rivera",
			firstName: "A.",
			lastName: "Rivera",
			mentorType: "teacher",
			mentorBio:
				"Yearbook editor and photography mentor who loves capturing campus life and teaching creative storytelling.",
			teacherTitle: "Ms.",
			teacherRoom: "3",
			teacherAvailabilityNotes: "Visual Arts — Mon after school",
		},
		settings: defaultSettings(),
	},
	{
		id: 114,
		email: "lnguyen@wcusd.org",
		password: MOCK_PASSWORD,
		role: "teacher" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Mrs. Nguyen",
			firstName: "L.",
			lastName: "Nguyen",
			mentorType: "teacher",
			mentorBio:
				"Debate coach passionate about current events, strong arguments, and helping students find their voice.",
			teacherTitle: "Mrs.",
			teacherRoom: "17",
			teacherAvailabilityNotes: "Speech & Debate — Tue/Thu after school",
		},
		settings: defaultSettings(),
	},
	{
		id: 115,
		email: "alewis@wcusd.org",
		password: MOCK_PASSWORD,
		role: "teacher" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Mr. Lewis",
			firstName: "A.",
			lastName: "Lewis",
			mentorType: "teacher",
			mentorBio:
				"Jazz director who arranges student pieces, collects vinyl, and brings guest artists to campus.",
			teacherTitle: "Mr.",
			teacherRoom: "Multi-Purpose Room",
			teacherAvailabilityNotes: "Music — Thu after school",
		},
		settings: defaultSettings(),
	},
	{
		id: 116,
		email: "amorales@wcusd.org",
		password: MOCK_PASSWORD,
		role: "teacher" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Dr. Morales",
			firstName: "A.",
			lastName: "Morales",
			mentorType: "teacher",
			mentorBio:
				"Environmental scientist who leads our sustainability projects and weekend community clean-ups.",
			teacherTitle: "Dr.",
			teacherRoom: "West Quad",
			teacherAvailabilityNotes: "Science & Sustainability — Fri lunch",
		},
		settings: defaultSettings(),
	},
	{
		id: 117,
		email: "sortiz@wcusd.org",
		password: MOCK_PASSWORD,
		role: "teacher" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Ms. Ortiz",
			firstName: "S.",
			lastName: "Ortiz",
			mentorType: "teacher",
			mentorBio:
				"Computer science teacher who loves hackathons, UI design critiques, and pairing students with tech mentors.",
			teacherTitle: "Ms.",
			teacherRoom: "18",
			teacherAvailabilityNotes: "Computer Science — Mon/Wed lunch",
		},
		settings: defaultSettings(),
	},
	{
		id: 118,
		email: "kcollins@wcusd.org",
		password: MOCK_PASSWORD,
		role: "teacher" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Mrs. Collins",
			firstName: "K.",
			lastName: "Collins",
			mentorType: "teacher",
			mentorBio:
				"Theater director who juggles staging, costumes, and student playwright workshops with a lot of enthusiasm.",
			teacherTitle: "Mrs.",
			teacherRoom: "Gym",
			teacherAvailabilityNotes: "Performing Arts — Tue after school",
		},
		settings: defaultSettings(),
	},
	{
		id: 119,
		email: "dhart@wcusd.org",
		password: MOCK_PASSWORD,
		role: "teacher" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Mr. Hart",
			firstName: "D.",
			lastName: "Hart",
			mentorType: "teacher",
			mentorBio:
				"Makerspace facilitator who adores rapid prototyping, woodworking, and student-led invention challenges.",
			teacherTitle: "Mr.",
			teacherRoom: "31",
			teacherAvailabilityNotes: "Engineering & Design — Thu after school",
		},
		settings: defaultSettings(),
	},
	{
		id: 120,
		email: "rramirez@wcusd.org",
		password: MOCK_PASSWORD,
		role: "teacher" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Ms. Ramirez",
			firstName: "R.",
			lastName: "Ramirez",
			mentorType: "teacher",
			mentorBio:
				"Community liaison who plans culture nights, potlucks, and peer-led conversations about identity.",
			teacherTitle: "Ms.",
			teacherRoom: "15",
			teacherAvailabilityNotes: "Community Programs — Wed lunch",
		},
		settings: defaultSettings(),
	},
	{
		id: 121,
		email: "mlopez@wcusd.org",
		password: MOCK_PASSWORD,
		role: "teacher" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Mrs. Lopez",
			firstName: "M.",
			lastName: "Lopez",
			mentorType: "teacher",
			mentorBio:
				"STEM coordinator focused on mentorship, hands-on labs, and connecting students with career pathways.",
			teacherTitle: "Mrs.",
			teacherRoom: "16",
			teacherAvailabilityNotes: "STEM Pathways — Mon after school",
		},
		settings: defaultSettings(),
	},
	{
		id: 122,
		email: "bmeyers@wcusd.org",
		password: MOCK_PASSWORD,
		role: "teacher" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Coach Meyers",
			firstName: "B.",
			lastName: "Meyers",
			mentorType: "teacher",
			mentorBio:
				"Outdoor enthusiast, trail runner, and weekend trip leader who teaches students adventure skills.",
			teacherTitle: "Coach",
			teacherRoom: "North Quad",
			teacherAvailabilityNotes: "Physical Education — mornings",
		},
		settings: defaultSettings(),
	},

	{
		id: 201,
		email: "vince.alvar@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Vince Alvar",
			firstName: "Vince",
			lastName: "Alvar",
			grade: "8",
			mentorType: "student",
			mentorBio:
				"I'm part of the soccer team, love math tutoring, and enjoy drone photography.",
			bio: "I'm part of the soccer team, love math tutoring, and enjoy drone photography.",
			interests: ["soccer", "math tutoring", "drone photography"],
		},
		settings: defaultSettings(),
	},
	{
		id: 202,
		email: "marco.browne@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Marco Browne",
			firstName: "Marco",
			lastName: "Browne",
			grade: "8",
			mentorType: "student",
			mentorBio: "I'm into coding club, basketball, and making music.",
			bio: "I'm into coding club, basketball, and making music.",
			interests: ["coding club", "basketball", "music"],
		},
		settings: defaultSettings(),
	},
	{
		id: 203,
		email: "winston.chan@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Winston Chan",
			firstName: "Winston",
			lastName: "Chan",
			grade: "8",
			mentorType: "student",
			mentorBio: "I love origami, math team, and gardening after school.",
			bio: "I love origami, math team, and gardening after school.",
			interests: ["origami", "math team", "gardening"],
		},
		settings: defaultSettings(),
	},
	{
		id: 204,
		email: "alex.hu@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Alex Hu",
			firstName: "Alex",
			lastName: "Hu",
			grade: "8",
			mentorType: "student",
			mentorBio: "I'm passionate about robotics, CAD design, and cycling.",
			bio: "I'm passionate about robotics, CAD design, and cycling.",
			interests: ["robotics", "CAD", "cycling"],
		},
		settings: defaultSettings(),
	},
	{
		id: 205,
		email: "jax.lorin@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Jax Lorin",
			firstName: "Jax",
			lastName: "Lorin",
			grade: "8",
			mentorType: "student",
			mentorBio: "I love esports, streaming design, and UI/UX.",
			bio: "I love esports, streaming design, and UI/UX.",
			interests: ["esports", "streaming", "UI/UX"],
		},
		settings: defaultSettings(),
	},
	{
		id: 206,
		email: "ian.rios@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Ian Rios",
			firstName: "Ian",
			lastName: "Rios",
			grade: "8",
			mentorType: "student",
			mentorBio: "I'm in Maker Club and love 3D printing and soccer.",
			bio: "I'm in Maker Club and love 3D printing and soccer.",
			interests: ["maker club", "3D printing", "soccer"],
		},
		settings: defaultSettings(),
	},
	{
		id: 207,
		email: "andy.wang@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Andy Wang",
			firstName: "Andy",
			lastName: "Wang",
			grade: "8",
			mentorType: "student",
			mentorBio: "I enjoy building web projects, joining hackathons, and playing badminton.",
			bio: "I enjoy building web projects, joining hackathons, and playing badminton.",
			interests: ["web dev", "hackathons", "badminton"],
		},
		settings: defaultSettings(),
	},
	{
		id: 208,
		email: "nadia.wong@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Nadia Wong",
			firstName: "Nadia",
			lastName: "Wong",
			grade: "8",
			mentorType: "student",
			mentorBio: "I'm into graphic design, environmental club, and digital art.",
			bio: "I'm into graphic design, environmental club, and digital art.",
			interests: ["graphic design", "environmental club", "digital art"],
		},
		settings: defaultSettings(),
	},
	{
		id: 209,
		email: "mikey.lam@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Mikey Lam",
			firstName: "Mikey",
			lastName: "Lam",
			grade: "8",
			mentorType: "student",
			mentorBio: "I love science tutoring, volleyball, and collecting mechanical keyboards.",
			bio: "I love science tutoring, volleyball, and collecting mechanical keyboards.",
			interests: ["tutoring", "volleyball", "keyboards"],
		},
		settings: defaultSettings(),
	},
	{
		id: 210,
		email: "jake.bymaster@wcusd.net",
		password: MOCK_PASSWORD,
		role: "student" as AccountRole,
		createdAt: MOCK_CREATED_AT,
		profile: {
			displayName: "Jake Bymaster",
			firstName: "Jake",
			lastName: "Bymaster",
			grade: "8",
			mentorType: "student",
			mentorBio: "I love Science Olympiad and the Robotics club.",
			bio: "I love Science Olympiad and the Robotics club.",
			interests: ["science", "robotics", "coding"],
		},
		settings: defaultSettings(),
	},
];
