export type From = "in" | "out";

export interface Message {
	id: number;
	from: From;
	text: string;
}

const now = new Date().toLocaleString();
const nowUnix = Date.now();
import profilePicture from "@/assets/placeholder-profile.svg";

export interface Person {
	id: number;
	name: string;
	type: "peer" | "teacher";
	grade?: number;
	hasConnected: boolean;
	requestedCommunication?: boolean;
	bio: string;
	profilePicture: string;
	email?: string;
	conversation: Message[];
	lastMessage: string;
	lastMessageUnix: number;
	roomNumber?: string;
	department?: string;
}
export interface Message {
	id: number;
	from: "in" | "out";
	text: string;
}

export interface Student {
	id: number;
	name: string;
	grade?: number;
	assignedToMentor: boolean;
	hasConnected: boolean;
	requestedCommunication?: boolean;
	bio: string;
	profilePicture: string;
	email?: string;
	conversation: Message[];
	lastMessage: string;
	lastMessageUnix: number;
}

export const students: Student[] = [
	{
		id: 101,
		name: "Avery Kim",
		grade: 8,
		assignedToMentor: true,
		hasConnected: false,
		bio: "I enjoy robotics, science fairs, and exploring how machines work. Excited to join STEM Club!",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 102,
		name: "Marcus Tran",
		grade: 7,
		assignedToMentor: true,
		hasConnected: false,
		bio: "I love playing soccer, coding small games, and building things with my friends.",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 103,
		name: "Sophie Li",
		grade: 6,
		assignedToMentor: false,
		hasConnected: false,
		bio: "I'm new to coding but love drawing, baking, and solving puzzles. Excited to make new friends!",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 104,
		name: "Noah Garcia",
		grade: 8,
		assignedToMentor: false,
		hasConnected: false,
		bio: "I'm part of band and enjoy practicing guitar, helping with stage crew, and trying out 3D printing.",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 105,
		name: "Mia Patel",
		grade: 7,
		assignedToMentor: false,
		hasConnected: false,
		bio: "I love art and design, journaling, and volunteering for school events.",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 106,
		name: "Ethan Reyes",
		grade: 8,
		assignedToMentor: false,
		hasConnected: false,
		bio: "I enjoy math challenges, robotics, and helping my classmates learn coding basics.",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 107,
		name: "Zara Thompson",
		grade: 6,
		assignedToMentor: false,
		hasConnected: false,
		bio: "I'm into digital art, reading fantasy novels, and learning photography.",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 108,
		name: "Leo Chen",
		grade: 7,
		assignedToMentor: false,
		hasConnected: false,
		bio: "I'm into robotics, coding challenges, and building model rockets with my friends.",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 109,
		name: "Aria Johnson",
		grade: 8,
		assignedToMentor: false,
		hasConnected: false,
		bio: "I love creative writing, theater, and leading small group projects at school.",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 110,
		name: "Caleb Nguyen",
		grade: 6,
		assignedToMentor: false,
		hasConnected: false,
		bio: "I enjoy soccer, experimenting with Arduino kits, and building fun contraptions at home.",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 111,
		name: "Isabella Rivera",
		grade: 7,
		assignedToMentor: false,
		hasConnected: false,
		bio: "I'm interested in journalism, photography, and storytelling through visuals.",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 112,
		name: "Liam Morales",
		grade: 8,
		assignedToMentor: false,
		hasConnected: false,
		bio: "I'm passionate about environmental science, student leadership, and recycling projects.",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 113,
		name: "Chloe Park",
		grade: 6,
		assignedToMentor: false,
		hasConnected: false,
		bio: "I love animals, art club, and learning to code small games in Scratch.",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 114,
		name: "Owen Flores",
		grade: 7,
		assignedToMentor: false,
		hasConnected: false,
		bio: "I'm into robotics, gaming, and learning about how computers actually work.",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 115,
		name: "Luna Delgado",
		grade: 8,
		assignedToMentor: false,
		hasConnected: false,
		bio: "I enjoy theater, dance, and creative storytelling. Excited to meet new people this year!",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 116,
		name: "Eli Ross",
		grade: 7,
		assignedToMentor: false,
		hasConnected: false,
		bio: "I'm into robotics, hiking, and exploring how technology can solve real problems.",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 117,
		name: "Naomi Wu",
		grade: 6,
		assignedToMentor: false,
		hasConnected: false,
		bio: "I love drawing, piano, and exploring fun science experiments at home.",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 118,
		name: "Jackson Lee",
		grade: 8,
		assignedToMentor: false,
		hasConnected: false,
		bio: "I'm a member of chess club, coding club, and I like building mechanical projects with my dad.",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 119,
		name: "Sophia Martinez",
		grade: 7,
		assignedToMentor: false,
		hasConnected: false,
		bio: "I love graphic design, yearbook club, and collaborating on group art projects.",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 120,
		name: "Gabriel Torres",
		grade: 8,
		assignedToMentor: false,
		hasConnected: false,
		bio: "I'm interested in engineering, video editing, and helping out in tech crew events.",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
];
export const mentors: Person[] = [
	{
		id: 1,
		name: "Mr. Miguel Barrios",
		type: "teacher",
		hasConnected: true,
		bio: "I'm passionate about STEM outreach, love a good poker night, and spend weekends hiking. Excited to help students discover hands-on robotics.",
		profilePicture: profilePicture,
		email: "mbarrios@wcusd.org",
		roomNumber: "6",
		department: "Science",
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 2,
		name: "Ms. June Choi",
		type: "teacher",
		hasConnected: false,
		bio: "I teach history and love exploring art, solving puzzles, and talking about the past in fun ways.",
		profilePicture: profilePicture,
		email: "jchoi@wcusd.org",
		roomNumber: "12",
		department: "History",
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 3,
		name: "Ms. Prisha Chiang",
		type: "teacher",
		hasConnected: false,
		bio: "I'm all about bringing art into the classroom. I help with yearbook and love working on community murals.",
		profilePicture: profilePicture,
		email: "pchiang@wcusd.org",
		roomNumber: "4B",
		department: "Visual Arts",
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 4,
		name: "Ms. Marina Cisneros",
		type: "teacher",
		hasConnected: false,
		bio: "I'm passionate about creative writing, student journalism, and fostering a love of reading.",
		profilePicture: profilePicture,
		email: "mcisneros@wcusd.org",
		roomNumber: "17",
		department: "English Language Arts",
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 5,
		name: "Mr. Daniel Eich",
		type: "teacher",
		hasConnected: false,
		bio: "I love mentoring students for science fairs, gardening on campus, and showcasing robotics projects.",
		profilePicture: profilePicture,
		email: "deich@wcusd.org",
		roomNumber: "18",
		department: "Science",
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 6,
		name: "Mr. Paul Fischer",
		type: "teacher",
		hasConnected: false,
		bio: "History bowl coach and avid hiker who loves visiting museums with students.",
		profilePicture: profilePicture,
		email: "pfischer@wcusd.org",
		roomNumber: "13",
		department: "Social Studies",
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 7,
		name: "Ms. Kat Garcia",
		type: "teacher",
		hasConnected: false,
		bio: "I work in counseling and love mindfulness, student leadership, and helping students find their path.",
		profilePicture: profilePicture,
		email: "kgarcia@wcusd.org",
		roomNumber: "Counseling",
		department: "Counseling & Student Support",
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 8,
		name: "Ms. Isa Salazar",
		type: "teacher",
		hasConnected: false,
		bio: "STEM educator who loves science labs, introducing students to coding, and going on hikes.",
		profilePicture: profilePicture,
		email: "isalazar@wcusd.org",
		roomNumber: "10",
		department: "STEM",
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 9,
		name: "Mr. Gabe Vela",
		type: "teacher",
		hasConnected: false,
		bio: "I mentor robotics teams, work with younger students, and spend weekends playing soccer.",
		profilePicture: profilePicture,
		email: "gvela@wcusd.org",
		roomNumber: "15",
		department: "Engineering & Technology",
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 10,
		name: "Mr. Shawn Villa",
		type: "teacher",
		hasConnected: false,
		bio: "I run the tech help desk and love esports and photography.",
		profilePicture: profilePicture,
		email: "svilla@wcusd.org",
		roomNumber: "32",
		department: "Information Technology",
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 11,
		name: "Ms. Chen",
		type: "teacher",
		hasConnected: false,
		bio: "I guide our robotics teams, love tinkering with microcontrollers, and host weekly build nights in the tech lab.",
		profilePicture: profilePicture,
		email: "mchen@wcusd.org",
		roomNumber: "32",
		department: "Engineering & Robotics",
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 12,
		name: "Mr. Patel",
		type: "teacher",
		hasConnected: false,
		bio: "Student leadership advisor focused on empowering voices, planning community events, and growing confident change-makers.",
		profilePicture: profilePicture,
		email: "vpatel@wcusd.org",
		roomNumber: "Counseling",
		department: "Student Leadership",
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 13,
		name: "Ms. Rivera",
		type: "teacher",
		hasConnected: false,
		bio: "Yearbook editor and photography mentor who loves capturing campus life and teaching creative storytelling.",
		profilePicture: profilePicture,
		email: "arivera@wcusd.org",
		roomNumber: "3",
		department: "Visual Arts",
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 14,
		name: "Mrs. Nguyen",
		type: "teacher",
		hasConnected: false,
		bio: "Debate coach passionate about current events, strong arguments, and helping students find their voice.",
		profilePicture: profilePicture,
		email: "lnguyen@wcusd.org",
		roomNumber: "17",
		department: "Speech & Debate",
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 15,
		name: "Mr. Lewis",
		type: "teacher",
		hasConnected: false,
		bio: "Jazz director who arranges student pieces, collects vinyl, and brings guest artists to campus.",
		profilePicture: profilePicture,
		email: "alewis@wcusd.org",
		roomNumber: "Multi-Purpose Room",
		department: "Music",
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 16,
		name: "Dr. Morales",
		type: "teacher",
		hasConnected: false,
		bio: "Environmental scientist who leads our sustainability projects and weekend community clean-ups.",
		profilePicture: profilePicture,
		email: "amorales@wcusd.org",
		roomNumber: "West Quad",
		department: "Science & Sustainability",
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 17,
		name: "Ms. Ortiz",
		type: "teacher",
		hasConnected: false,
		bio: "Computer science teacher who loves hackathons, UI design critiques, and pairing students with tech mentors.",
		profilePicture: profilePicture,
		email: "sortiz@wcusd.org",
		roomNumber: "18",
		department: "Computer Science",
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 18,
		name: "Mrs. Collins",
		type: "teacher",
		hasConnected: false,
		bio: "Theater director who juggles staging, costumes, and student playwright workshops with a lot of enthusiasm.",
		profilePicture: profilePicture,
		email: "kcollins@wcusd.org",
		roomNumber: "Gym",
		department: "Performing Arts",
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 19,
		name: "Mr. Hart",
		type: "teacher",
		hasConnected: false,
		bio: "Makerspace facilitator who adores rapid prototyping, woodworking, and student-led invention challenges.",
		profilePicture: profilePicture,
		email: "dhart@wcusd.org",
		roomNumber: "31",
		department: "Engineering & Design",
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 20,
		name: "Ms. Ramirez",
		type: "teacher",
		hasConnected: false,
		bio: "Community liaison who plans culture nights, potlucks, and peer-led conversations about identity.",
		profilePicture: profilePicture,
		email: "rramirez@wcusd.org",
		roomNumber: "15",
		department: "Community Programs",
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 21,
		name: "Mrs. Lopez",
		type: "teacher",
		hasConnected: false,
		bio: "STEM coordinator focused on mentorship, hands-on labs, and connecting students with career pathways.",
		profilePicture: profilePicture,
		email: "mlopez@wcusd.org",
		roomNumber: "16",
		department: "STEM Pathways",
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 22,
		name: "Coach Meyers",
		type: "teacher",
		hasConnected: false,
		bio: "Outdoor enthusiast, trail runner, and weekend trip leader who teaches students adventure skills.",
		profilePicture: profilePicture,
		email: "bmeyers@wcusd.org",
		roomNumber: "North Quad",
		department: "Physical Education",
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},

	{
		id: 101,
		name: "Vince Alvar",
		type: "peer",
		grade: 8,
		hasConnected: false,
		bio: "I'm part of the soccer team, love math tutoring, and enjoy drone photography.",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 102,
		name: "Marco Browne",
		type: "peer",
		grade: 8,
		hasConnected: false,
		bio: "I'm into coding club, basketball, and making music.",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 103,
		name: "Winston Chan",
		type: "peer",
		grade: 8,
		hasConnected: false,
		bio: "I love origami, math team, and gardening after school.",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 105,
		name: "Alex Hu",
		type: "peer",
		grade: 8,
		hasConnected: false,
		bio: "I'm passionate about robotics, CAD design, and cycling.",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 107,
		name: "Jax Lorin",
		type: "peer",
		grade: 8,
		hasConnected: false,
		bio: "I love esports, streaming design, and UI/UX.",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 110,
		name: "Ian Rios",
		type: "peer",
		grade: 8,
		hasConnected: false,
		bio: "I'm in Maker Club and love 3D printing and soccer.",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 113,
		name: "Andy Wang",
		type: "peer",
		grade: 8,
		hasConnected: false,
		bio: "I enjoy building web projects, joining hackathons, and playing badminton.",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 114,
		name: "Nadia Wong",
		type: "peer",
		grade: 8,
		hasConnected: false,
		bio: "I'm into graphic design, environmental club, and digital art.",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
	{
		id: 120,
		name: "Mikey Lam",
		type: "peer",
		grade: 8,
		hasConnected: true,
		bio: "I love science tutoring, volleyball, and collecting mechanical keyboards.",
		profilePicture: profilePicture,
		conversation: [],
		lastMessage: now,
		lastMessageUnix: nowUnix,
	},
];
